name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: building for produciton
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: yarn install
        
